modLoader="javafml"
loaderVersion="[36,)"
license="Not specified"

[[mods]]
modId="naruto_unleashed"
version="1.0.0"
displayName="Naruto Unleashed"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="19494, MCreator"

[[dependencies.naruto_unleashed]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




